when:
  event: [push, manual]

skip_clone: false

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: ghcr.io 
      repo: ghcr.io/${CI_REPO_OWNER}/datapack-generator
      tags: latest
      platforms: linux/amd64,linux/arm64,linux/arm/v7
      username: hpf3
      password:
        from_secret: ghcr_token
  trigger-portainer:
    image: curlimages/curl:latest
    environment:
      WEBHOOK:
        from_secret: webhook
    commands:
      - curl -sS -X POST "$WEBHOOK"
